container:
  image: swipl:latest
    
task:
  skip: "!changesInclude('*.pro')"
  matrix:
    - name: test001
      only_if: "changesInclude(euler001.pro)"
      env:
        PRO: euler001.pro
        PROGOAL: 'euler001([3,5],999,233168)'
    - name: test002
      only_if: "changesInclude(euler002.pro)"
      env:
        PRO: euler002.pro
        PROGOAL: 'euler002(4000000,2,4613732)'
    - name: test003
      only_if: "changesInclude(euler003.pro)"
      env:
        PRO: euler003.pro
        PROGOAL: 'euler003(600851475143,6857)'
    - name: test005
      only_if: "changesInclude(euler005.pro)"
      env:
        PRO: euler005.pro
        PROGOAL: 'euler005([1,20],232792560)'
    - name: test006
      only_if: "changesInclude(euler006.pro)"
      env:
        PRO: euler006.pro
        PROGOAL: 'euler006(100,25164150)'
    - name: test009
      only_if: "changesInclude(euler009.pro)"
      env:
        PRO: euler009.pro
        PROGOAL: 'once(euler009([[200,375,425],31875000],1000))'
  test_script: swipl -q -s $PRO -g $PROGOAL -t halt